version: '3.9'

services:
  mongo-db:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: feruza1727
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - Staffer
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ ping: 1 })'"]
      interval: 30s
      timeout: 10s
      retries: 5

  company-service:
    container_name: timeline
    build: .
    depends_on:
      - mongo-db

    ports:
      - "8060:8060"
    networks:
      - Staffer
    environment:
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_USER=feruza
      - MONGO_PASSWORD=feruza1727
      - MONGO_DB=timecapsule
      - KAFKA_BROKER=kafka:9092

networks:
  Staffer:
      external: true
      name: Time
      driver: bridge


volumes:
  mongo-data:
